### ISSUE TITLE
Use Forward Secrecy on HTTPS connection

### ISSUE THREAD

**Issue by stefanw** [ZeitOnline/briefkasten#11]
Use [Forward Secrecy](http://www.zeit.de/digital/datenschutz/2013-09/perfect-forward-secrecy) on the HTTPS connection.

This is not an issue with the software itself, but with the deployment. An appropriate key exchange algorithm could be ECDHE_RSA.

**Comment by neuhaus** [comment]
Wow, I can't believe this issue hasn't been fixed in over a year, considering how easy it is to fix!

Also, enable TLS 1.2, TLS 1.1 and disable RC4!

**Comment by neuhaus** [comment]
When you switch from a SHA1 to SHA256 certificate, you should publish the SHA256 fingerprint instead of the SHA1 fingerprint and update the file `briefkasten/templates/fingerprint.pt` accordingly.

**Comment by tomster** [comment]
i should note for the record, that the setup of the public facing webserver is not within the scope of this project.

the issue has been brought to the attention of the administrators of the host but beyond that there's not really much more that you and i can do here on this issue.

i am, however, keeping this issue open as a 'sore reminder' and will happily close it, once the host has achieved at least a 'B' rating at ssllabs :-)

**Comment by neuhaus** [comment]
Quote:
> *i should note for the record, that the setup of the public facing webserver is not within the scope of this project.*

The public facing webserver is **as important as the rest of the system**! It could be the weakest link in the whole setup. If it is attacked successfully, it could tell the whistleblower to put the data onto the system of the attacker instead of the super secure real system.
That way, the system would be completely compromised.

Equivalent: You must securei the web form, not just the "action" URL in the form, otherwise the request that delivers the form can be modified and the data gets hijacked.

**Comment by tomster** [comment]
@neuhaus what can i say? i agree entirely.

**Comment by tomster** [comment]
@neuhaus just to clarify: in fact, the public facing webserver *is* part of this project and we try to adhere to current best practices (see ``roles/webserver``) – it just so happens that the briefkasten instance at ZON uses a different webserver which is administrated independently.

**Comment by neuhaus** [comment]
@tomster OK thank you for clarifying this.

**Comment by tomster** [comment]
ok, as of today, the ssl instance in front of the briefkasten has received an update and now featuers an `A` grade on ssllabs - thanks to the new admin at ZON :)

![zonbkssllabs_small](https://cloud.githubusercontent.com/assets/59207/13112509/3f1de354-d58b-11e5-9a4f-b1245389f5eb.png)
