### ISSUE TITLE
Apache2 SSL Proxy  in front of briefkasten

### ISSUE THREAD

**Issue by BethkePeter** [ZeitOnline/briefkasten#14]
Hi,
I have got the briefkasten application working with Protocal http and Port 6543.
Now I try to secure the traffic with SSL.
I am using an  Apache webserver as an Reverse-Proxy.
With an sed output-filter I was able to rewrite the link in the Application, but the Email has still got an link to the webserver with http://xxxxxx, not https

What do I have to change to get the reply_url to point to https:/xxxx, in the application and EMail.

kind regards.
Peter

**Comment by tomster** [comment]
thanks for the feedback, hope it helps others, too
