### ISSUE TITLE
Did not get pdf or doc Files in the Email

### ISSUE THREAD

**Issue by BethkePeter** [ZeitOnline/briefkasten#15]
Hi Support Team,

My pgp is working, I get the emails encrypted und I can decrypte the E-Mail.
if i attache an jpeg File the EMail has got an attachment but I am not able to get the picture back.

If I attach  an pdf or an doc File, then i do not get an attachment in the E-Mail.

Do i need some Software on my Server to work with attachements ?

**Comment by tomster** [comment]
guess this can be closed now :)

**Comment by BethkePeter** [comment]
Yes. You can close the issue.

kind regards,

Peter Bethke



-----Ursprüngliche Nachricht-----
Von: Tom Lazar <notifications@github.com>
Gesendet: Mit 17 Februar 2016 15:33
An: ZeitOnline/briefkasten <briefkasten@noreply.github.com>
CC: Peter Bethke <bethke@msu.biz>
Betreff: Re: [briefkasten] Did not get pdf or doc Files in the Email (#15)

guess this can be closed now :)
