### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by zon-ops** [ZeitOnline/briefkasten#282]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Awaiting Schedule

These updates are awaiting their schedule. Click on a checkbox to get an update now.

 - [ ] chore(deps): update zeitonline/gh-action-workflows action to v1.3
 - [ ] chore(deps): update actions/checkout action to v3
 - [ ] chore(deps): update github/codeql-action action to v2
 - [ ] chore(deps): lock file maintenance

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [chore(deps): update dependency click to v8.1.5](../pull/292)
 - [ ] [chore(deps): update dependency pyyaml to v6.0.1](../pull/294)

## Detected dependencies

<details><summary>dockerfile</summary>
<blockquote>

<details><summary>Dockerfile</summary>

 - `python 3.11.4-slim`

</details>

</blockquote>
</details>

<details><summary>github-actions</summary>
<blockquote>

<details><summary>.github/workflows/backend-tests.yaml</summary>

 - `zeitonline/gh-action-workflows 1.0`

</details>

<details><summary>.github/workflows/codeql-analysis.yml</summary>

 - `actions/checkout v2`
 - `github/codeql-action v1`
 - `github/codeql-action v1`
 - `github/codeql-action v1`

</details>

<details><summary>.github/workflows/docs-trigger-build.yaml</summary>

 - `peter-evans/repository-dispatch v2`

</details>

</blockquote>
</details>

<details><summary>pep621</summary>
<blockquote>

<details><summary>watchdog/src/watchdog/pyproject.toml</summary>

</details>

</blockquote>
</details>

<details><summary>pip_requirements</summary>
<blockquote>

<details><summary>application/requirements.txt</summary>

 - `Chameleon ==4.0.1`
 - `click ==8.1.4`
 - `colander ==2.0`
 - `cssselect ==1.2.0`
 - `diazo ==1.5.0`
 - `future ==0.18.3`
 - `humanfriendly ==10.0`
 - `hupper ==1.12`
 - `iso8601 ==2.0.0`
 - `itsdangerous ==2.1.2`
 - `Jinja2 ==3.1.2`
 - `lxml ==4.9.3`
 - `MarkupSafe ==2.1.3`
 - `Paste ==3.5.3`
 - `PasteDeploy ==3.0.1`
 - `plaster ==1.1.2`
 - `plaster-pastedeploy ==1.0.1`
 - `pyramid ==2.0.1`
 - `pyramid-chameleon ==0.3`
 - `python-gnupg ==0.5.0`
 - `PyYAML ==6.0`
 - `repoze.xmliter ==0.6.1`
 - `six ==1.16.0`
 - `translationstring ==1.4`
 - `venusian ==3.0.0`
 - `watchdog ==3.0.0`
 - `WebOb ==1.8.7`
 - `zope.deprecation ==5.0`
 - `zope.interface ==6.0`

</details>

<details><summary>deployment/roles/briefkasten/files/requirements.txt</summary>

 - `Chameleon ==4.0.1`
 - `click ==8.1.4`
 - `colander ==2.0`
 - `cssselect ==1.2.0`
 - `diazo ==1.5.0`
 - `future ==0.18.3`
 - `humanfriendly ==10.0`
 - `hupper ==1.12`
 - `iso8601 ==2.0.0`
 - `itsdangerous ==2.1.2`
 - `Jinja2 ==3.1.2`
 - `lxml ==4.9.3`
 - `MarkupSafe ==2.1.3`
 - `Paste ==3.5.3`
 - `PasteDeploy ==3.0.1`
 - `plaster ==1.1.2`
 - `plaster-pastedeploy ==1.0.1`
 - `pyramid ==2.0.1`
 - `pyramid-chameleon ==0.3`
 - `python-gnupg ==0.5.0`
 - `PyYAML ==6.0`
 - `repoze.xmliter ==0.6.1`
 - `six ==1.16.0`
 - `translationstring ==1.4`
 - `venusian ==3.0.0`
 - `watchdog ==3.0.0`
 - `WebOb ==1.8.7`
 - `zope.deprecation ==5.0`
 - `zope.interface ==6.0`

</details>

</blockquote>
</details>

<details><summary>pip_setup</summary>
<blockquote>

<details><summary>application/setup.py</summary>

 - `Pyramid <2.1`
 - `tox <5.0`

</details>

</blockquote>
</details>

<details><summary>pipenv</summary>
<blockquote>

<details><summary>application/Pipfile</summary>

</details>

<details><summary>deployment/Pipfile</summary>

</details>

<details><summary>watchdog/Pipfile</summary>

</details>

</blockquote>
</details>

**Comment by witsch** [comment]
Mit #295 gibt's noch ein zweites Dashboard (und ich mach dieses deswegen mal zu)…
