### ISSUE TITLE
Run metadata stripping processes in a sandbox

### ISSUE THREAD

**Issue by alech** [ZeitOnline/briefkasten#7]
It might make sense to run the metadata stripping processes in a sandbox or as a different user, as they run scripts which parse attacker controlled data. Vulnerabilities in image or PDF parsing libraries are a possibility and would allow an attacker access to other whistleblower's data in the current setting.

**Comment by tomster** [comment]
with #18 we now have true sandboxing for the cleansing. while we're a) still on FreeBSD (which, btw has ASLR by now, thankyouvermyuch) and b) we still haven't used something like @DrWhax recommended I'm closing this issue as far as the sandboxing is concerned.
